apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-api-master
  namespace: fiapx
  labels:
    app: locust-api
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-api
      role: master
  template:
    metadata:
      labels:
        app: locust-api
        role: master
    spec:
      containers:
        - name: locust
          image: locustio/locust:latest
          ports:
            - containerPort: 8089
              name: web
            - containerPort: 5557
              name: master
          env:
            - name: LOCUST_MODE
              value: "master"
            - name: LOCUST_HOST
              value: "http://api-service:3001"
            - name: LOCUST_LOGLEVEL
              value: "INFO"
          volumeMounts:
            - name: locust-script
              mountPath: /home/locust
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          command:
            - "locust"
            - "--master"
            - "--web-host=0.0.0.0"
            - "--web-port=8089"
      volumes:
        - name: locust-script
          configMap:
            name: locust-api-script
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-api-worker
  namespace: fiapx
  labels:
    app: locust-api
    role: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: locust-api
      role: worker
  template:
    metadata:
      labels:
        app: locust-api
        role: worker
    spec:
      containers:
        - name: locust
          image: locustio/locust:latest
          env:
            - name: LOCUST_MODE
              value: "worker"
            - name: LOCUST_MASTER_NODE_HOST
              value: "locust-api-master"
            - name: LOCUST_MASTER_NODE_PORT
              value: "5557"
            - name: LOCUST_LOGLEVEL
              value: "INFO"
          volumeMounts:
            - name: locust-script
              mountPath: /home/locust
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          command:
            - "locust"
            - "--worker"
            - "--master-host=locust-api-master"
            - "--master-port=5557"
      volumes:
        - name: locust-script
          configMap:
            name: locust-api-script

