apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: fiapx
spec:
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-app
          image: vineco/api-fiapx-11soat:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secret