apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: fiapx
type: Opaque
stringData:
  # Database Password
  DB_PASSWORD: "${API_DB_PASSWORD}"
  DATABASE_URL: "${API_DATABASE_URL}"

  # RabbitMQ Password
  RABBITMQ_PASSWORD: "${API_RABBITMQ_PASSWORD}"

  # AWS Credentials
  AWS_ACCESS_KEY_ID: "${API_AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"

  # JWT Secret
  JWT_SECRET: "${API_JWT_SECRET}"

