apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service
  namespace: fiapx
spec:
  selector:
    matchLabels:
      app: worker-service
  template:
    metadata:
      labels:
        app: worker-service
    spec:
      containers:
        - name: worker-app
          image: luckmenez/worker_fiapx_11soat:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          envFrom:
            - configMapRef:
                name: worker-config
            - secretRef:
                name: worker-secret

