apiVersion: v1
kind: Secret
metadata:
  name: worker-secret
  namespace: fiapx
type: Opaque
stringData:
  # RabbitMQ Configuration
  RABBITMQ_PASSWORD: "${RABBITMQ_DEFAULT_PASS}"
  RABBITMQ_URL: "amqp://admin:${RABBITMQ_DEFAULT_PASS}@rabbitmq-service:5672"

  # AWS Credentials
  AWS_ACCESS_KEY_ID: "${WORKER_AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${WORKER_AWS_SECRET_ACCESS_KEY}"