apiVersion: v1
kind: Service
metadata:
  name: worker-service
  namespace: fiapx
spec:
  type: LoadBalancer
  selector:
    app: worker-service
  ports:
    - name: http
      protocol: TCP
      port: 82
      targetPort: 3002