apiVersion: v1
kind: Service
metadata:
  name: worker-service
  namespace: fiapx
spec:
  type: ClusterIP
  selector:
    app: worker-service
  ports:
    - name: http
      protocol: TCP
      port: 3002
      targetPort: 3002