apiVersion: v1
kind: Service
metadata:
  name: locust-master
  namespace: fiapx
  labels:
    app: locust
    role: master
spec:
  selector:
    app: locust
    role: master
  ports:
    - name: web
      protocol: TCP
      port: 8089
      targetPort: 8089
    - name: master
      protocol: TCP
      port: 5557
      targetPort: 5557
  type: ClusterIP